### ISSUE TITLE
Exporting Phone Numbers to CSV file

### ISSUE THREAD

**Issue by joedinsmoor** [joedinsmoor/sqlite_scraper#3]
phone_numbers logger adds each digit of phone number to its own row

- [ ] Understand why this happens
- [ ] Recursive reset of iterative character

**Comment by phoenixrising1800** [comment]
This thread may be helpful: [StackOverflow](https://stackoverflow.com/questions/15129567/csv-writer-writing-each-character-of-word-in-separate-column-cell)  

So perhaps for logger.py: the writerow() call in phone_numbers() should be changed to: `writer.writerow([str])`, since square brackets around the 'str' argument signify a sequence rather than individual characters?

**Comment by joedinsmoor** [comment]
> This thread may be helpful: [StackOverflow](https://stackoverflow.com/questions/15129567/csv-writer-writing-each-character-of-word-in-separate-column-cell)
> 
> So perhaps for logger.py: the writerow() call in phone_numbers() should be changed to: `writer.writerow([str])`, since square brackets around the 'str' argument signify a sequence rather than individual characters?

This worked! Thank you!
